csblog/csblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login as auth_login

from bookmarks.views import (
    main_page, 
    user_page, 
    popular_page,
    logout_page, 
    register_page, 
    bookmark_save_page,
    bookmark_vote_page,
    tag_page,
    tag_cloud_page,
    search_page,
    bookmark_page,
    ajax_tag_autocomplete,
    friends_page,
    friend_add,
    friend_invite,
    friend_accept
    )
from django.views.static import serve
# from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView

import os
site_media = os.path.join(
    os.path.dirname(__file__), 'site_media'
)

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Browsing
    url(r'^$', main_page),
    url(r'^user/(\w+)/$', user_page),
    url(r'^popular/$', popular_page),

    # Session management
    # url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^login/$', auth_login),
    url(r'^logout/$', logout_page),
    url(r'^register/$', register_page),
    # url(r'^register/success/$', direct_to_template, {'template': 'registration/register_success.html'}), 
    url(r'^register/success/$', TemplateView.as_view(template_name="registration/register_success.html")), 
    # url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': site_media}),

    # Account management
    url(r'^save/$', bookmark_save_page),
    url(r'^vote/$', bookmark_vote_page),
    url(r'^tag/([^\s]+)/$', tag_page),
    url(r'^tag/$', tag_cloud_page),
    url(r'^bookmark/(\d+)/$', bookmark_page),

    url(r'^search/$', search_page),
    url(r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),

    url(r'^comments/',include('django_comments.urls')),

    url(r'^friends/(\w+)/$', friends_page),
    url(r'^friend/add/$', friend_add),
    url(r'^friend/invite/$', friend_invite),
    url(r'^friend/accept/(\w+)/$', friend_accept),


    # Site media
    url(r'^site_media/(?P<path>.*)$', serve, {'document_root': site_media}),
]

csblog/bookmarks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Link(models.Model):
    url = models.URLField(unique=True)

    def __unicode__(self):
        return self.url
        
class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)    

    def __unicode__(self):
        return '%s, %s' % (self.user.username, self.link.url)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)

    def __unicode__(self):
        return self.name  

class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)

    def __unicode__(self):
        return u'%s, %s' % (self.bookmark, self.votes)        

class Friendship(models.Model):
    from_friend = models.ForeignKey(
        User, related_name='friend_set'
    )
    to_friend = models.ForeignKey(
        User, related_name='to_friend_set'
    )
    def __unicode__(self):
        return u'%s, %s' % (
        self.from_friend.username,
        self.to_friend.username
    )
    class Meta:
        unique_together = (('to_friend', 'from_friend'), )   
        permissions = (
            ('can_list_friend_bookmarks', 'Can list friend bookmarks'),
        )     

from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings

class Invitation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(User)
    def __unicode__(self):
        return u'%s, %s' % (self.sender.username, self.email)     

    def send(self):
        subject = u'Invitation to join Django Bookmarks'
        link = 'http://%s/friend/accept/%s/' % (
            settings.SITE_HOST,
            self.code
        )
        template = get_template('invitation_email.txt')
        context = {   
            'name': self.name,
            'link': link,
            'sender': self.sender.username,
            }
        message = template.render(context)
        send_mail(
            subject, message,
            settings.DEFAULT_FROM_EMAIL, [self.email]
        )

csblog/templates/base.html
<html>
    <head>
        <title>Django Bookmarks |
        {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
        <script type="text/javascript" src="/site_media/jquery.js"></script>
        {% block external %}{% endblock %}
    </head>
    <body>
        <div id="nav">
            <a href="/">home</a> |
            <a href="/popular/">popular</a> |
            {% if user.is_authenticated %}
                <a href="/save/">submit</a> |
                <a href="/search/">search</a> |
                <a href="/user/{{ user.username }}/">
                    {{ user.username }}</a> |
                <a href="/logout/">logout</a>
            {% else %}
                <a href="/login/">login</a>
                <a href="/register/">register</a>
            {% endif %}
        </div>
        <h1>{% block head %}{% endblock %}</h1>
        
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        {% block content %}{% endblock %}
    </body>
</html>

csblog/templates/bookmark_list.html
{% if bookmarks %}
    <ul class="bookmarks">
        {% for bookmark in bookmarks %}
        <li>
            <a href="{{ bookmark.link.url }}" class="title">
            {{ bookmark.title }}</a>
            <br>
            {% if show_edit %}
            <a href="/save/?url={{ bookmark.link.url|urlencode }}" class="edit">[edit]</a>
            {% endif %}
            {% if show_tags %}
                Tags:
                {% if bookmark.tag_set.all %}
                    <ul class="tags">
                    {% for tag in bookmark.tag_set.all %}
                        <li>
                            <a href="/tag/{{ tag.name }}/">{{ tag.name|urlencode }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    None.
                {% endif %}
                <br />
            {% endif %}
            {% if show_user %}
                Posted by:
                <a href="/user/{{ bookmark.user.username }}/"
                class="username">
                {{ bookmark.user.username }}</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% if show_paginator %}
        <div class="paginator">
            {% if has_prev %}
                <a href="?page={{ prev_page }}">&laquo; Previous</a>
            {% endif %}
            {% if has_next %}
                <a href="?page={{ next_page }}">Next &raquo;</a>
            {% endif %}
            (Page {{ page }} of {{ pages }})
        </div>
    {% endif %}
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

csblog/templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}

{% block title %}
    Bookmark: {{ shared_bookmark.bookmark.title }}
{% endblock %}
{% block head %}
    <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
    <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
    {{ shared_bookmark.bookmark.title }}</a>
{% endblock %}
{% block content %}
    Posted By:
    <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">
    {{ shared_bookmark.bookmark.user.username }}</a> |
    <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
    <h2>Comments</h2>
    {% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}
    {% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}
    {% for comment in comment_list %}
        <div class="comment">
            <p><b>{{ comment.user.username }}</b> said:</p>
            {{ comment.comment|escape|urlizetrunc:40|linebreaks }}
        </div>
    {% endfor %}
    <p>Number of comments: {{ comment_count }}</p>
    {% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id %}
{% endblock %}

csblog/templates/bookmark_save.html
{% extends "base.html" %}

{% block external %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/site_media/tag_autocomplete.js"></script>
{% endblock %}
{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}
{% block content %}
    {% include "bookmark_save_form.html" %}
{% endblock %}

csblog/templates/bookmark_save_form.html
<form id="save-form" method="post" action="/save/">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save" />
</form>

csblog/templates/friend_invite.html
{% extends "base.html" %}
{% block title %}Invite A Friend{% endblock %}
{% block head %}Invite A Friend{% endblock %}
{% block content %}
    Enter your friend name and email below,
    and click "send invite" to invite your friend to join the site:
    <form method="post" action=".">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send invite" />
    </form>
{% endblock %}

csblog/templates/friends_page.html
{% extends "base.html" %}
{% block title %}Friends for {{ username }}{% endblock %}
{% block head %}Friends for {{ username }}{% endblock %}
{% block content %}
    <h2>Friend List</h2>
    {% if friends %}
        <ul class="friends">
            {% for friend in friends %}
                <li><a href="/user/{{ friend.username }}/">
                {{ friend.username }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No friends found.</p>
    {% endif %}
    <a href="/friend/invite/">Invite a friend!</a>
    <h2>Latest Friend Bookmarks</h2>
    {% include "bookmark_list.html" %}
{% endblock %}

csblog/templates/main_page.html
{% extends "base.html" %}

{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block content %}
    {% if user.username %}
      <p>Welcome {{ user.username }}!
      Here you can store and share bookmarks!</p>
    {% else %}
      <p>Welcome anonymous user!
      You need to <a href="/login/">login</a>
      before you can store and share bookmarks.</p>
    {% endif %}
    <h2>Bookmarks Shared by Users</h2>
    {% include "shared_bookmark_list.html" %}    
{% endblock %}

csblog/templates/popular_page.html
{% extends "base.html" %}
{% block title %}Popular Bookmarks{% endblock %}
{% block head %}Popular Bookmarks{% endblock %}
{% block content %}
    {% include "shared_bookmark_list.html" %}
{% endblock %}

csblog/templates/search.html
{% extends "base.html" %}
{% block external %}
<script type="text/javascript" src="/site_media/search.js"></script>
{% endblock %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block content %}
    <form id="search-form" method="get" action=".">
        {{ form.as_p }}
        <input type="submit" value="search" />
    </form>
    <div id="search-results">
    {% if show_results %}
        {% include 'bookmark_list.html' %}
    {% endif %}
    </div>
{% endblock %}

csblog/templates/shared_bookmark_list.html
{% if shared_bookmarks %}
    <ul class="bookmarks">
        {% for shared_bookmark in shared_bookmarks %}
        <li>
            <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
            <a href="{{ shared_bookmark.bookmark.link.url }}" class="title"> {{ shared_bookmark.bookmark.title }}</a>
            <br />
            Posted By:
            <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username"> {{ shared_bookmark.bookmark.user.username }}</a> |
            <span class="vote-count">Votes:{{ shared_bookmark.votes }}</span>
            <a href="/bookmark/{{ shared_bookmark.id }}/">Comments</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

csblog/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block content %}
    <div id="tag-cloud">
    {% for tag in tags %}
        <a href="/tag/{{ tag.name }}/"
        class="tag-cloud-{{ tag.weight }}">
        {{ tag.name|urlencode }}</a>
    {% endfor %}
    </div>
{% endblock %}

csblog/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name }}{% endblock %}
{% block head %}Bookmarks for tag: {{ tag_name }}{% endblock%}
{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}

csblog/templates/user_page.html
{% extends "base.html" %}
{% block external %}
<script type="text/javascript" src="/site_media/bookmark_edit.js"></script>
{% endblock %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}
{% block content %}
    {% ifequal user.username username %}
        <a href="/friends/{{ username }}/">view your friends</a>
    {% else %}
        {% if is_friend %}
            <a href="/friends/{{ user.username }}/">{{ username }} is a friend of yours</a>
        {% else %}
            <a href="/friend/add/?username={{ username }}">add {{ username }} to your friends</a>
        {% endif %}
        - <a href="/friends/{{ username }}/">view {{username }}'s friends</a>
    {% endifequal %}

    {% include "bookmark_list.html" %}
{% endblock %}